# version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: inventory-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///./inventory.db
    volumes:
      # - ./backend/inventory.db:/app/inventory.db
      - ./backend/uploaded_files:/app/uploaded_files
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - inventory-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: inventory-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://202.112.47.35:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge

volumes:
  db_data:
    driver: local